#!/bin/bash

echo "init system"
if [[ -v ENABLE_SSH ]]; then
    echo "=> ENABLE_SSH set to ${ENABLE_SSH}"
    if [ ! -d /var/run/sshd ] ; then
        echo "=> Configuring SSH"
        mkdir /var/run/sshd
        sed 's/PermitRootLogin without-password/PermitRootLogin yes/' -i /etc/ssh/sshd_config
        sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
        #sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        #sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
    fi
    if [ ! -f ~/supervisord.ssh ] ; then
        echo "=> Adding SSH to Supervisord"
        touch ~/supervisord.ssh
        echo "[program:sshd]" >> /etc/supervisor/supervisord.conf
        echo "command=/usr/sbin/sshd -D -E /var/log/sshd.log" >>/etc/supervisor/supervisord.conf
        echo "autostart=true" >>/etc/supervisor/supervisord.conf
        echo "autorestart=true" >>/etc/supervisor/supervisord.conf
        echo "redirect_stderr=true" >>/etc/supervisor/supervisord.conf
        echo "stdout_logfile=/var/log/%(program_name)s.log" >>/etc/supervisor/supervisord.conf
        echo "stdout_logfile_maxbytes=5MB" >>/etc/supervisor/supervisord.conf
        echo "stdout_logfile_backups=0" >>/etc/supervisor/supervisord.conf
        echo "stderr_logfile=/var/log/%(program_name)s.log" >>/etc/supervisor/supervisord.conf
        echo "stderr_logfile_maxbytes=5MB" >>/etc/supervisor/supervisord.conf
        echo "stderr_logfile_backups=0" >>/etc/supervisor/supervisord.conf
        echo " " >>/etc/supervisor/supervisord.conf
    fi
fi

echo "=> Starting Supervisor - the Process Control System"
echo " "
/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf