#!/bin/bash

echo "-> System Initialization"
if [[ -v ENABLE_SSH ]]; then
    echo "=> ENABLE_SSH set to ${ENABLE_SSH}"
    if [ ! -d /var/run/sshd ] ; then
        echo "=> Configuring SSH"
        mkdir /var/run/sshd
        sed 's/PermitRootLogin without-password/PermitRootLogin yes/' -i /etc/ssh/sshd_config
        sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
    fi
    if [ ! -f ~/supervisord.ssh ] ; then
        echo "=> Adding SSH to Supervisord"
        touch ~/supervisord.ssh
        echo " " >> /etc/supervisor/supervisord.conf
        echo "[program:sshd]" >> /etc/supervisor/supervisord.conf
        echo "command=/usr/sbin/sshd -D -E /var/log/sshd.log" >>/etc/supervisor/supervisord.conf
        echo "autostart=true" >>/etc/supervisor/supervisord.conf
        echo "autorestart=true" >>/etc/supervisor/supervisord.conf
        echo "redirect_stderr=true" >>/etc/supervisor/supervisord.conf
        echo "stdout_logfile=/var/log/%(program_name)s.log" >>/etc/supervisor/supervisord.conf
        echo "stdout_logfile_maxbytes=5MB" >>/etc/supervisor/supervisord.conf
        echo "stdout_logfile_backups=0" >>/etc/supervisor/supervisord.conf
        echo "stderr_logfile=/var/log/%(program_name)s.log" >>/etc/supervisor/supervisord.conf
        echo "stderr_logfile_maxbytes=5MB" >>/etc/supervisor/supervisord.conf
        echo "stderr_logfile_backups=0" >>/etc/supervisor/supervisord.conf
        echo " " >>/etc/supervisor/supervisord.conf
    fi
fi

if [ -v AUTO_START ] ; then
    echo "=> Adding creepMiner to Supervisord"
    touch ~/supervisord.creepminer
    echo " " >> /etc/supervisor/supervisord.conf
    echo "[program:creepMiner]" >> /etc/supervisor/supervisord.conf
    if [ -f /config/mining.conf ] ; then
        echo "command=/usr/local/sbin/creepMiner --c=/config/mining.conf" >>/etc/supervisor/supervisord.conf
    else
        echo "command=/usr/local/sbin/creepMiner --c=/usr/local/sbin/mining.conf" >>/etc/supervisor/supervisord.conf
    fi
    echo "autostart=true" >>/etc/supervisor/supervisord.conf
    echo "autorestart=true" >>/etc/supervisor/supervisord.conf
    echo "directory=/usr/local/sbin" >>/etc/supervisor/supervisord.conf
    echo "stdout_logfile=/dev/stdout" >>/etc/supervisor/supervisord.conf
    echo "stdout_logfile_maxbytes=0" >>/etc/supervisor/supervisord.conf
fi

echo "=> Starting Supervisor - the Process Control System"

/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf